### PR TITLE
YTEP-0033: dropping Python 2.7 support

### PR DESCRIPTION
**Pull request by ngoldbaum**
See the text of the YTEP for details.

### CODE REVIEW

**Comment by matthewturk** [comment]
Seems like the right thing to do.  Then we can get started replacing every `def` with `async def` for ease of debugging.  Thanks for writing this up and taking it on!

**Comment by bwkeller** [comment]
This would certainly simplify my life, since I would only have to maintain the python3-yt deb package.  +1

**Comment by chummels** [comment]
+1

**Comment by hugovk** [comment]
By the way, Python 2.7 EOL is 2020-01-01, not 2020-04-20.

https://github.com/python/devguide/pull/344

**Pull request merged**
